import time
def warn(text):
    print(f"[WARNING] {text}")
def error(text):
    print(f"[ERROR] {text}")
def info(text):
    print(f"[INFO] {text}")
def notice(text):
    print(f"[NOTICE] {text}")
def debug(text):
    print(f"[DEBUG] {text}")
def log(text):
    print(f"[LOG] {text}")